/* eslint-disable @next/next/no-img-element */
/* eslint-disable jsx-a11y/alt-text */
import Head from "next/head";
import Link from "next/link";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <img
            className={styles.myImg}
            src="/images.png"
            alt="hunting coder"
            width={150}
            height={150}
          />
          <h1 className={styles.title}>
            <span className="dummy">&lt;maitriCoder/&gt;</span>
          </h1>

          <div>
            <div className="blogs">
              <h2 className={styles.h2}>Latest Blogs</h2>
              <div>
                <h3 className={styles.h3}>How to learn JavaScript in 2022?</h3>
                <p>
                  JavaScript is the language use to design logic for the web
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Saepe
                  incidunt iure velit voluptatibus explicabo excepturi earum
                  soluta inventore doloremque dolorum?
                </p>
                <button className={styles.btn}>Read More</button>
              </div>
            </div>
            <div className="blogs">
              <div>
                <h3 className={styles.h3}>How to learn JavaScript in 2022?</h3>
                <p className={styles.p}>
                  JavaScript is the language use to design logic for the web
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed
                  nobis necessitatibus incidunt soluta. Mollitia, error?
                </p>
                <button className={styles.btn}>Read More</button>
              </div>
            </div>
            <div className="blogs">
              <div>
                <h3 className={styles.h3}>How to learn JavaScript in 2022?</h3>
                <p>
                  JavaScript is the language use to design logic for the web
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse
                  cum, sequi tenetur ullam saepe, est in totam, molestias quo
                  inventore exercitationem dignissimos. Rerum, assumenda ab.
                </p>
                <button className={styles.btn}>Read More</button>
              </div>
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
